# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
- repo: self
variables:
  dockerfilePath: '$(Build.SourcesDirectory)/src/Dockerfile'
  webRepository: 'web'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'
stages:
- stage: Build
  displayName: Build and publish Java container
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    variables:
    - group: Release
   # - task: AzureMysqlDeployment@1
#displayName: Run MySQL initialization script
  #inputs:
    azureSubscription: 'Azure Connection'
    serverName: '$(MySqlServer).mysql.database.azure.com'
    databaseName: 'alm'
    sqlUsername: $(MySqlUserName)@$(MySqlServer)
    sqlPassword: $(MySqlPassword)
    sqlFile: '$(Build.SourcesDirectory)/CreateMYSQLDB.sql'
